// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0--rc1
// source: completionevent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletionEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType        int32   `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Timestamp        int64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SurveyId         int32   `protobuf:"varint,3,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	QuestionId       int32   `protobuf:"varint,4,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	MismatchedReason int32   `protobuf:"varint,5,opt,name=mismatched_reason,json=mismatchedReason,proto3" json:"mismatched_reason,omitempty"`
	OptionIds        []int32 `protobuf:"varint,6,rep,packed,name=option_ids,json=optionIds,proto3" json:"option_ids,omitempty"`
	Geo              string  `protobuf:"bytes,7,opt,name=geo,proto3" json:"geo,omitempty"`
	Lang             string  `protobuf:"bytes,8,opt,name=lang,proto3" json:"lang,omitempty"`
	Gender           int32   `protobuf:"varint,9,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *CompletionEvent) Reset() {
	*x = CompletionEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_completionevent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionEvent) ProtoMessage() {}

func (x *CompletionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_completionevent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionEvent.ProtoReflect.Descriptor instead.
func (*CompletionEvent) Descriptor() ([]byte, []int) {
	return file_completionevent_proto_rawDescGZIP(), []int{0}
}

func (x *CompletionEvent) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *CompletionEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CompletionEvent) GetSurveyId() int32 {
	if x != nil {
		return x.SurveyId
	}
	return 0
}

func (x *CompletionEvent) GetQuestionId() int32 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *CompletionEvent) GetMismatchedReason() int32 {
	if x != nil {
		return x.MismatchedReason
	}
	return 0
}

func (x *CompletionEvent) GetOptionIds() []int32 {
	if x != nil {
		return x.OptionIds
	}
	return nil
}

func (x *CompletionEvent) GetGeo() string {
	if x != nil {
		return x.Geo
	}
	return ""
}

func (x *CompletionEvent) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *CompletionEvent) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

var File_completionevent_proto protoreflect.FileDescriptor

var file_completionevent_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x96, 0x02, 0x0a, 0x0f,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x6d, 0x69,
	0x73, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x6d, 0x69, 0x73, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x64, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x65, 0x6f, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x65, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x42, 0x36, 0x5a, 0x34, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d,
	0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2d, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_completionevent_proto_rawDescOnce sync.Once
	file_completionevent_proto_rawDescData = file_completionevent_proto_rawDesc
)

func file_completionevent_proto_rawDescGZIP() []byte {
	file_completionevent_proto_rawDescOnce.Do(func() {
		file_completionevent_proto_rawDescData = protoimpl.X.CompressGZIP(file_completionevent_proto_rawDescData)
	})
	return file_completionevent_proto_rawDescData
}

var file_completionevent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_completionevent_proto_goTypes = []interface{}{
	(*CompletionEvent)(nil), // 0: pb.CompletionEvent
}
var file_completionevent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_completionevent_proto_init() }
func file_completionevent_proto_init() {
	if File_completionevent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_completionevent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletionEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_completionevent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_completionevent_proto_goTypes,
		DependencyIndexes: file_completionevent_proto_depIdxs,
		MessageInfos:      file_completionevent_proto_msgTypes,
	}.Build()
	File_completionevent_proto = out.File
	file_completionevent_proto_rawDesc = nil
	file_completionevent_proto_goTypes = nil
	file_completionevent_proto_depIdxs = nil
}
